# Generated by Django 5.0.6 on 2024-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_defaultrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrecipe',
            name='image_url',
            field=models.CharField(default='imageurl', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='imageurl', max_length=500),
        ),
    ]
